[Error] 2020-01-24 11:43:21 Failed to connect to MySQL:Nem hozható létre kapcsolat, mert a célszámítógép már visszautasította a kapcsolatot.

[Error] 2020-01-28 12:58:22 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:45:53 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:46:01 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:46:02 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:46:03 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:46:04 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:46:11 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:46:55 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:48:32 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:48:33 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:48:35 Failed to connect to MySQL:Access denied for user 'phpalapok'@'localhost' (using password: YES)
[Error] 2020-02-01 19:52:33 Failed to connect to MySQL:Unknown database 'phpalapok'
[Error] 2020-02-01 19:52:34 Failed to connect to MySQL:Unknown database 'phpalapok'
